// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bandwidth limit configuration for a single process.
 */
export type BandwidthLimit = { 
/**
 * Download limit in bytes per second (0 = unlimited).
 */
download_bps: number, 
/**
 * Upload limit in bytes per second (0 = unlimited).
 */
upload_bps: number, };

/**
 * Snapshot of one process's traffic state, serializable for the frontend.
 */
export type ProcessTrafficSnapshot = { pid: number, name: string, exe_path: string, 
/**
 * Upload speed in bytes/sec.
 */
upload_speed: number, 
/**
 * Download speed in bytes/sec.
 */
download_speed: number, 
/**
 * Cumulative bytes sent since monitoring started.
 */
bytes_sent: number, 
/**
 * Cumulative bytes received since monitoring started.
 */
bytes_recv: number, 
/**
 * Number of active connections (TCP + UDP).
 */
connection_count: number, };

/**
 * A saved bandwidth rule from the database.
 */
export type SavedRule = { exe_path: string, process_name: string, download_bps: number, upload_bps: number, blocked: boolean, };

/**
 * A single traffic history record.
 */
export type TrafficRecord = { timestamp: number, pid: number, process_name: string, exe_path: string, bytes_sent: number, bytes_recv: number, upload_speed: number, download_speed: number, };

/**
 * Summary of a process's total traffic over a time window.
 */
export type TrafficSummary = { process_name: string, exe_path: string, total_sent: number, total_recv: number, total_bytes: number, };
